name: Buildx latest
on:
  push:
    branches: [master]
    paths:
      - .github/workflows/buildx-latest.yml
      - cmd/**
      - internal/**
      - .dockerignore
      - .golangci.yml
      - Dockerfile
      - go.mod
      - go.sum
      - server.cfg
      - Dockerfile
      - steam.Dockerfile
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Buildx setup
        uses: crazy-max/ghaction-docker-buildx@v1
      - name: Dockerhub login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u qmcgaw --password-stdin 2>&1
      - name: Buildx Alpine image
        run: |
          docker buildx build \
            --progress plain \
            --platform=linux/amd64,linux/386 \
            --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
            --build-arg COMMIT=`git rev-parse --short HEAD` \
            --build-arg VERSION=latest \
            -t qmcgaw/cod4:alpine \
            -t qmcgaw/cod4:latest \
            --push \
            .
      - name: Buildx Debian Steam image
        run: |
          docker buildx build \
            --progress plain \
            --platform=linux/amd64,linux/386 \
            --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
            --build-arg COMMIT=`git rev-parse --short HEAD` \
            --build-arg VERSION=steam \
            -f steam.Dockerfile \
            -t qmcgaw/cod4:steam \
            --push \
            .
      - run: curl -X POST https://hooks.microbadger.com/images/qmcgaw/cod4/8mWxKyC34UYWUF7BRtDpbB8WWt4= || exit 0
