name: Docker build
on:
  pull_request:
    branches: [master]
    paths:
      - .github/workflows/build.yml
      - cmd/**
      - internal/**
      - .dockerignore
      - .golangci.yml
      - Dockerfile
      - go.mod
      - go.sum
      - server.cfg
      - Dockerfile
      - steam.Dockerfile
jobs:
  alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: docker build .
  debian:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -f steam.Dockerfile .
