name: PR Debian Docker build
on:
  pull_request:
    branches: [master]
    paths:
      - .github/workflows/pr-debian.yml
      - cmd/**
      - internal/**
      - .dockerignore
      - .golangci.yml
      - steam.Dockerfile
      - go.mod
      - go.sum
      - server.cfg

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -f steam.Dockerfile .
